# build ./Dockerfile and port 8888 to 8888

services:
  spec:
    build:
      context: .
      dockerfile: Dockerfile
    # mount the current directory to /home/scoped/notebooks
    #entrypoint:
    #  - tini -s -g -- /entry.sh /usr/bin/startup.sh
  pypaw:
    build:
      context: .
      dockerfile: Dockerfile_pypaw
    ports:
      - "8888:8888" # modify to 8888:8889 or another if 8888 is already in use
    volumes:
      - ./notebooks:/home/scoped/notebooks
