# build ./Dockerfile and port 8888 to 8888

services:
  spec:
    build:
      context: .
      #dockerfile: Dockerfile_spec_ubuntu
      dockerfile: Dockerfile_spec_frontera
  pypaw:
    build:
      context: .
      dockerfile: Dockerfile_pypaw
    ports:
      - "8888:8888" # modify to 8888:8889 or another if 8888 is already in use
    volumes:
      - ./notebooks:/home/jovyan/notebooks
