# base image which includes intel mpi/conda/jupyterla
FROM ghcr.io/seisscoped/container-base:centos7

#RUN yum install -y cmake3 boost-devel \
#    && ln -s /bin/cmake3 /bin/cmake

# go to /home/scoped
WORKDIR /home/scoped

# install parallel HDF5 with yum
RUN yum install -y hdf5-mpich

#
## install pypaw with conda env
RUN conda init bash \
    && . ~/.bashrc \
    && git clone --branch py3_add_project_function https://github.com/mnagaso/pypaw.git \
    && cd pypaw \
    && conda env create -f environment.yml \
    && conda activate pypaw \
    && CC=mpicc pip install --no-binary=mpi4py mpi4py \
    #&& rm -rf ./h5py && git clone https://github.com/h5py/h5py.git && cd h5py && HDF5_MPI=ON CC=mpicc pip install . && cd .. && rm -rf h5py \
    && CC=mpicc pip install --no-binary=h5py h5py \
    && pip install . \
    && cd ../

# install ipykernel for pyenv
RUN conda init bash \
    && . ~/.bashrc \
    && conda activate pypaw \
    && conda install -y ipykernel \
    && python -m ipykernel install --user --name=pypaw_ipykernel


