# base image which includes intel mpi/conda/jupyterla
FROM ubuntu:23.04

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    git \
    cmake \
    gfortran \
    gcc \
    libhdf5-openmpi-dev \
    libboost-all-dev \
    && apt-get clean

# go to /home/scoped
WORKDIR /home/scoped


# HDF5_DIR for pypaw
ENV HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/openmpi
# add hdf5 bin to PATH
ENV PATH=$PATH:/usr/lib/x86_64-linux-gnu/hdf5/openmpi/bin
# add hdf5 lib to LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib

RUN git clone https://github.com/SeismicData/asdf-library.git \
    && cd asdf-library \
    && mkdir build && cd build \
    && FFLAGS="-fallow-argument-mismatch" cmake .. -DCMAKE_Fortran_COMPILER=h5pfc -DCMAKE_INSTALL_PREFIX=/home/scoped/asdf -DBUILD_DOCUMENTATION=False \
    && make && make install \
    && cd ../../ \
    && rm -rf asdf-library

# install ADIOS2
RUN git clone https://github.com/ornladios/ADIOS2.git && cd ADIOS2 \
    && mkdir build && cd build\
    && cmake .. -DCMAKE_INSTALL_PREFIX=/home/scoped/adios2 \
    && make -j4 && make install \
    && cd ../../ && rm -rf ADIOS2
ENV PATH=$PATH:/home/scoped/adios2/bin

COPY ./DATA_in /home/scoped/DATA_in

# compile specfem3d_globe
RUN git clone --recursive --branch devel https://github.com/SPECFEM/specfem3d_globe.git \
    && cd specfem3d_globe \
    && cp -r /home/scoped/DATA_in/* ./DATA/ \
    && cp ./DATA/mk_gen.sh ./ \
    && ./configure --enable-vectorization \
        --with-adios2 ADIOS2_CONFIG=/home/scoped/adios2/bin/adios2-config \
        --with-asdf 'ASDF_LIBS=-L/home/scoped/asdf/lib -L/usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib -L/home/scoped/hdf5/lib' \
        MPIFC=mpif90 FC=gfortran CC=gcc \
        'FLAGS_CHECK=-O2 -mcmodel=medium -Wunused -Waliasing -Wampersand -Wcharacter-truncation -Wline-truncation -Wsurprising -Wno-tabs -Wunderflow' \
        CFLAGS="-std=c99" \
    && ./mk_gen.sh 1 \
    #&& make all \
    && cd ../

# add specfem3d_globe/bin to PATH
ENV PATH=$PATH:/home/scoped/specfem3d_globe/bin

RUN mkdir -p /home/scoped/sim_dir/OUTPUT_FILES \
    && mkdir -p /home/scoped/sim_dir/DATA \
    && mkdir -p /home/scoped/sim_dir/DATABASES_MPI \
    && cp -r /home/scoped/specfem3d_globe/DATA/* /home/scoped/sim_dir/DATA/

# change home directory to /home/scoped/sim_dir
#
WORKDIR /home/scoped/sim_dir